import { Command } from "commander";
import * as fs from "fs";
import * as path from "path";
import ora from "ora";
import chalk from "chalk";
import { createClient } from "../lib/api";

export const pullCommand = new Command("pull")
  .description("Pull secrets from Envcrypt into a local .env file")
  .requiredOption("-p, --project <slug>", "Project slug")
  .option("-e, --env <environment>", "Environment", "development")
  .option("-o, --output <file>", "Output file", ".env")
  .option("--overwrite", "Overwrite existing .env file", false)
  .action(async (options) => {
    const spinner = ora(
      `Pulling ${options.env} secrets for ${options.project}...`,
    ).start();

    try {
      const client = createClient();
      const res = await client.get(
        `/projects/${options.project}/secrets/${options.env}`,
      );
      const secrets: { key: string; value: string }[] = res.data;

      if (secrets.length === 0) {
        spinner.warn(chalk.yellow("No secrets found"));
        return;
      }

      const outputPath = path.resolve(process.cwd(), options.output);

      // Merge with existing .env if not overwriting
      let existing: Record<string, string> = {};
      if (!options.overwrite && fs.existsSync(outputPath)) {
        const content = fs.readFileSync(outputPath, "utf-8");
        content.split("\n").forEach((line) => {
          const [k, ...v] = line.split("=");
          if (k && v.length) existing[k.trim()] = v.join("=").trim();
        });
      }

      // Build .env content
      const merged = { ...existing };
      secrets.forEach((s) => {
        merged[s.key] = s.value;
      });

      const lines = [
        `# Generated by Envcrypt — ${new Date().toISOString()}`,
        `# Project: ${options.project} | Environment: ${options.env}`,
        `# Do not commit this file to git`,
        "",
        ...Object.entries(merged).map(([k, v]) =>
          v.includes(" ") || v.includes("#") ? `${k}="${v}"` : `${k}=${v}`,
        ),
      ];

      fs.writeFileSync(outputPath, lines.join("\n") + "\n");

      spinner.succeed(
        chalk.green(`Pulled ${secrets.length} secrets → ${options.output}`),
      );

      // Show what was pulled
      console.log("");
      secrets.forEach((s) => {
        console.log(
          `  ${chalk.gray("+")} ${chalk.cyan(s.key)} ${chalk.gray("→")} ${chalk.gray("••••••")}`,
        );
      });
      console.log("");
    } catch (err: any) {
      spinner.fail(chalk.red("Failed to pull secrets"));
      if (err.response?.data?.message) {
        console.error(chalk.red(err.response.data.message));
      }
      process.exit(1);
    }
  });
