export function Terminal() {
  return (
    <section id="how-it-works" className="max-w-3xl mx-auto px-6 mb-24">
      <div className="bg-gray-950 rounded-xl overflow-hidden border border-gray-800">
        <div className="flex items-center gap-1.5 px-4 py-3 border-b border-gray-800">
          <span className="w-3 h-3 rounded-full bg-red-500 opacity-70" />
          <span className="w-3 h-3 rounded-full bg-yellow-500 opacity-70" />
          <span className="w-3 h-3 rounded-full bg-green-500 opacity-70" />
          <span className="text-gray-500 text-xs ml-2 font-mono">terminal</span>
        </div>
        <div className="p-6 font-mono text-sm space-y-3">
          <div>
            <span className="text-gray-500">$ </span>
            <span className="text-green-400">envcrypt login</span>
          </div>
          <div className="text-gray-400 pl-2">Logged in as you@company.com</div>

          <div className="pt-2">
            <span className="text-gray-500">$ </span>
            <span className="text-green-400">
              envcrypt pull --project my-api --env production
            </span>
          </div>
          <div className="text-gray-400 pl-2 space-y-1">
            <div>
              <span className="text-green-500">✓</span> Pulled 6 secrets → .env
            </div>
            <div className="pl-4 space-y-0.5 text-gray-500">
              <div>
                + <span className="text-cyan-400">DATABASE_URL</span> → ••••••
              </div>
              <div>
                + <span className="text-cyan-400">REDIS_URL</span> → ••••••
              </div>
              <div>
                + <span className="text-cyan-400">JWT_SECRET</span> → ••••••
              </div>
              <div>
                + <span className="text-cyan-400">STRIPE_KEY</span> → ••••••
              </div>
              <div>
                + <span className="text-cyan-400">S3_BUCKET</span> → ••••••
              </div>
              <div>
                + <span className="text-cyan-400">SMTP_PASS</span> → ••••••
              </div>
            </div>
          </div>

          <div className="pt-2">
            <span className="text-gray-500">$ </span>
            <span className="text-green-400">cat .env</span>
          </div>
          <div className="text-gray-500 pl-2 space-y-0.5 text-xs">
            <div className="text-gray-600">
              # Generated by Envcrypt — 2026-03-16
            </div>
            <div>
              <span className="text-cyan-400">DATABASE_URL</span>
              =postgresql://prod:secret@db:5432/app
            </div>
            <div>
              <span className="text-cyan-400">REDIS_URL</span>
              =redis://prod-redis:6379
            </div>
            <div className="text-gray-600">...</div>
          </div>
        </div>
      </div>
    </section>
  );
}
